id: P008067
initial_creation_type: ocr
source_metadata:
  id: bdr:W21915
  title: གསོ་རིག་སྐོར་གྱི་རྒྱུན་མཁོ་གལ་ཆེ་བ་བདམས་བསྒྲིགས།
  author: ''
  volumes:
    b66fd0387ad64ddd98776f5b356d83d7:
      image_group_id: I1KG20642
      title: ''
      volume_number: 1
      total_pages: 448
ebook_metadata:
  title: གསོ་རིག་སྐོར་གྱི་རྒྱུན་མཁོ་གལ་ཆེ་བ་བདམས་བསྒྲིགས།
  author: ''
  sku: P008067
  cover: cover.jpg
  layers:
  - pagination
