id: P008067
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:59:13.457896
source_metadata:
  id: bdr:W21915
  title: གསོ་རིག་སྐོར་གྱི་རྒྱུན་མཁོ་གལ་ཆེ་བ་བདམས་བསྒྲིགས།
  author: ''
  volumes:
    40aebef8736d447f9492356f05661b88:
      image_group_id: I1KG20642
      title: Volume 1 of gso rig skor gyi rgyun mkho gal che ba bdams bsgrigs
      volume_number: 1
      total_pages: 448
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
